# This defines the rules for when a pipeline should run.
workflow:
  rules:
    # Don't run branch pipeline if an MR is open (only the MR pipeline will run)
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    # Run for merge requests
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Run scheduled pipeline for autoupdate or manually triggered pipeline
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"

stages:
  - build
  - test

# ---
.image:ubuntu:noble:
  image: ubuntu:noble
  before_script: &global_before_scripts
    - .ci/prepare-apt.sh

.image:pmOS:edge:
  image: alpine:edge
  before_script: &global_before_scripts
    - .ci/prepare-pmos.sh "master"

.image:pmOS:v25_06:
  image: alpine:3.22
  before_script: &global_before_scripts
    - .ci/prepare-pmos.sh "v25.06"

.build:pmOS:
  stage: build
  script:
    - ".ci/build-pmos.sh"
  after_script:
    - cp -r /home/build/packages/ packages/ || true
  artifacts:
    expire_in: 1 week
    paths:
      - packages/
      - build/
  timeout: 1 h

.build:ubuntu:
  stage: build
  script:
    - ".ci/build-apt.sh"
  artifacts:
    expire_in: 1 day
    paths:
      - build/

.test:pmOS:
  stage: test
  script:
    - ".ci/test-pmos.sh"
  artifacts:
    expire_in: 1 week
    paths:
      - build/meson-logs/

.test:ubuntu:
  stage: test
  script:
    - ".ci/test.sh"
  artifacts:
    expire_in: 1 week
    paths:
      - build/meson-logs/

# ---

build:ubuntu:noble:
  extends: [ ".build:ubuntu", ".image:ubuntu:noble"]

build:pmOS:v25_06:
  extends: [ ".build:pmOS", ".image:pmOS:v25_06" ]

build:pmOS:edge:
  extends: [ ".build:pmOS", ".image:pmOS:edge" ]

test:pmOS:v25_06:
  extends: [ ".test:pmOS", ".image:pmOS:v25_06" ]
  needs: [ "build:pmOS:v25_06" ]

test:pmOS:edge:
  extends: [ ".test:pmOS", ".image:pmOS:edge" ]
  needs: [ "build:pmOS:edge" ]

test:ubuntu:noble:
  extends: [ ".test:ubuntu", ".image:ubuntu:noble"]
